# Deploys when push is made that includes frontend directory
name: deploy_frontend

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azureresumesaclayton --auth-mode key -d '$web' -s frontend/ --overwrite
    
    - name: Remove files from Azure that are not present in repo
      uses: azure/CLI@v1
      with:
        inlineScript: |
          blobs=$(az storage blob list --container-name '$web' --account-name azureresumesaclayton --query "[].name" --output tsv | sort)
          echo "$blobs" > azure-blobs.txt

          pushd frontend
          local_files=$(find . -type f | sort | sed 's|^\./||')
          echo "$local_files" > local-files.txt
          popd

          comm -23 azure-blobs.txt local-files.txt | while read blob
          do
            az storage blob delete --container-name '$web' --name "$blob" --account-name 'azureresumesaclayton'
          done

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumecdn" --name "azureresumeclayton" --resource-group "AzureResumeRG"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()